### ISSUE TITLE
Timeout searching for location on Android (Nativescript 3.0.3)

### ISSUE THREAD

**Issue by clarenceh** [NativeScript/nativescript-geolocation#62]
I saw issues reported on forum and this repository about issues on reading location on Android on NS3.0. I just want to report that it also not working on Nativescript Sample application.

Steps to reproduce:
- Clone the NS sample app repo (https://github.com/NativeScript/nativescript-sdk-examples-ng)
- run `tns install`
- run `tns run android --emulator`
- go to the location sample and click read current location

The plugin runs fine on iOS.

Attached please found the screenshot for your reference.

Versions:
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.0.3           │ 3.0.3          │ Up to date  │
│ tns-core-modules │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-android      │ 3.0.1           │ 3.0.1          │ Up to date  │
│ tns-ios          │ 3.0.1           │ 3.0.1          │ Up to date  │

Hope this can help and let me know if need any further information.

Regards
Clarence
<img width="646" alt="ns-android-location-error" src="https://cloud.githubusercontent.com/assets/2868803/26813045/1df47b72-4aae-11e7-8c70-ca22bf492777.png">

**Comment by OPADA-Eng** [comment]
same thing happening with me. any help ?

**Comment by OPADA-Eng** [comment]
I noticed that sometimes the internet connection type may cause this problem so try to change internet provider.

**Comment by tbozhikov** [comment]
Hi @clarenceh, looking at the sceenshots I see that you are running the app on emulator. You might check the Location options/settings/controls of the emulator if you can "Send" location to the device like the Android emulator for Mac:
![image](https://user-images.githubusercontent.com/5127806/28219677-78685742-68c5-11e7-8945-6c4229d4558b.png)
Do you guys get the same exception when running the app on a physical device?

**Comment by dvdbrk** [comment]
Got the same problem. I don't think it has anything to do with emulator tho 😕

**Comment by marcelbraun1985** [comment]
I get the same error. iOS is working but Android unfortunately not.

**Comment by jaredjohnson59** [comment]
Has anybody found a solution for this issue on Android? I am still getting the following "JS: Error: Timeout while searching for location!"

**Comment by clarenceh** [comment]
@tbozhikov Sorry for my late reply. Yes I can send location to the emulator. I opened Google Map, and then in emulator's location setting, change the value for latitude and longitude, and the location on the map was updated successfully. Have you had a chance to check out the NS Angular examples and test it out as I mentioned in my message? I believe you will be able to re-produce this. Many thanks, Clarence

**Comment by jeremypele** [comment]
Got the same issue here. Tested on many emulators and many real devices.
Last one is on Android 7.0, wifi - network - gps enabled. Timeout on location almost anytime.

Using version 3.0 of the plugin

As for my dependencies:
```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.1.3           │ 3.1.3          │ Up to date  │
│ tns-core-modules │ 3.1.0           │ 3.1.0          │ Up to date  │
│ tns-android      │ 3.1.1           │ 3.1.1          │ Up to date  │
│ tns-ios          │ 3.1.0           │ 3.1.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by LeCaoPhuc** [comment]
Hi @jeremypele , i have error same thing, i fix with open Location( or GPS ) of device choose Location Mode is a Hight accuracy. A reason is your device auto turn on Battery saving move or Device only mode. it is slow in get location from GPS. that plugin working with android and ios with me, i think it not a prolem.
Hope this will help...

**Comment by jeremypele** [comment]
@LeCaoPhuc Regarding the different tests I've done this weekend: on a real device it works well when data is active. If gps + wifi are active then it's not working well - event if accuracy is set to the highest on device settings

**Comment by LeCaoPhuc** [comment]
@jeremypele  your mean is in real device, if you use data (3g,4g) and turn on gps then you always get location. but if use wifi to connect internet, location will slow and time out if accuracy not in highest .

**Comment by moayadnajd** [comment]
same thing happening with me. any help ?

**Comment by F481** [comment]
Same problem for me on real Galaxy S7 with Android 7.

**Comment by PerryRylance** [comment]
Hi have this problem on my Samsung A5

**Comment by F481** [comment]
Hi guys, please try to set the "desiredAccuracy" option to "Accuracy.high" (see https://docs.nativescript.org/hardware/location#getcurrentlocation).
That solved the problem for me 👍

**Comment by OPADA-Eng** [comment]
I have tried it and nothing changed

**Comment by TinoN** [comment]
I had the same problem as described. Apparently first you have to call `.watchLocation();`
I am using my device (XiaoMi 5S) directly without emulator.

So here is what I did (I practically called `.getCurrentLocation(...);` and `.clearWatch(watchId);` after `.watchLocation();`:

```
function buttonGetLocationTap(args) {
    if (!geolocation.isEnabled()) {
        geolocation.enableLocationRequest();
    }

    watchId = geolocation.watchLocation();

    var location = geolocation.getCurrentLocation({desiredAccuracy: 3, updateDistance: 5, timeout: 2000}).
    then(function(loc) {
        if (loc) {
            console.log("Latitude " + loc.latitude);
            console.log("Longitude " + loc.longitude);
            console.log("Altitude " + loc.altitude);
            console.log("Horizontal Accuracy " + loc.horizontalAccuracy);
            console.log("Vertical Accuracy " + loc.verticalAccuracy);
            console.log("Speed " + loc.speed);
            console.log("Direction " + loc.direction);
            console.log("Timestamp " + loc.timestamp);

            if (watchId) {
                geolocation.clearWatch(watchId);
            }
        }
    }, function(e){
        console.log("Error: " + e.message);
        if (watchId) {
            geolocation.clearWatch(watchId);
        }
    });
}
exports.buttonGetLocationTap = buttonGetLocationTap;
```

Hope it helps.
Regards!

**Comment by toeknee581** [comment]
Per TinoN's suggestion, I added this before my call to getCurrentLocation and it works.  Note, this is the typescript version:
let watchId = watchLocation(x => this.lastLocation = x, x => console.log(x), null);

**Comment by TinoN** [comment]
@toeknee581 I checked it again with my phone. It worked in the office where I have WiFi. As soon as I left the building and had only access to mobile network it didn't work. On my mobile phone I switched the phone location settings from "High accuracy" to "Device only" to force GPS only usage. The data was then most of the time retrieved reliably (sometimes the phone GPS couldn't be accessed...). But when I came back to my office I switched back the phone settings to "High accuracy" to make sure that GPS, WiFi or Mobile can be used to determine location. From then on it stopped working in the office.

So I agree with you, it is not working reliably and I also can't reproduce when it is working and when not...

**Comment by TinoN** [comment]
Hello,
I still was not able to get it to work. And I also couldn't figure out, what the actual problem in the nativescript-geolocation code might be. (too many callbacks for me :))
Therefore based on the nativescript-geolocation code I tried figuring out how to actually trigger the GeoLocation update for my android phone.
You can see the result [here](https://github.com/TinoN/tns-geoLoc).
You can see the usage of the Android API directly and trigger `requestSingleUpdate(...)` and `requestLocationUpdates(...)`.
Any comments, suggestions and/or questions are very welcome.
Regards!

**Comment by mohammadrafigh** [comment]
@TinoN1e unfortunately your code doesn't work on my phone Android 5.1 (I changed your permission function to fit my API level).

to clarify more about this issue: actually everything works fine with nativescript-geolocation in emulator when "Send" button inside emulator pressed. but I tried the same code on real devices with different android versions but no result with COARSE or FINE, watch or single update... I traced nativescript-geolocation completely and nothing is wrong here. also I wrote an example app like @TinoN1e to work directly with android APIs but it doesn't work neither. so I think maybe something is wrong with nativescript code or android runtime. I didn't try Fused Location API on android. maybe this works rather than using location manager. I will try it tomorrow and share the results.

**Comment by nmongiya** [comment]
I am also having the Timeout issue. I am using "nativescript-geolocation": "^3.0.1",

**Comment by mansured** [comment]
And on a real device too..

**Comment by lusocoding** [comment]
Same thing here, either with emulator (x86 with Google APIs) or using a real device (tested with Huawei TAG-L21 and Samsung J3). Regardless of the accuracy or using data vs wifi, never works and always have timeout errors as below. Send option on emulator has the same result.

"tns-core-modules": "3.1.1",
"nativescript-geolocation": "^3.0.1",
"tns-android": {
      "version": "3.2.0"
    }

```javascript
{
	"originalStack": "Error: Timeout while searching for location!\n    at ZoneAwareError (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:993:33)\n    at file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/nativescript-geolocation/geolocation.js:232:31\n    at invoke (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/tns-core-modules/timer/timer.js:19:48)\n    at ZoneDelegate.invoke (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:365:26)\n    at Object.onInvoke (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:3965:37)\n    at ZoneDelegate.invoke (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:364:32)\n    at Zone.runGuarded (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:138:47)\n    at file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:116:29\n    at Object.run (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/tns-core-modules/timer/timer.js:23:13)",
	"zoneAwareStack": "Error: Timeout while searching for location!\n    at file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/nativescript-geolocation/geolocation.js:232:31 [angular]\n    at invoke (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/tns-core-modules/timer/timer.js:19:48) [angular]\n    at Object.onInvoke (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:3965:37) [angular]\n    at file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:116:29 [<root>]\n    at Object.run (file:///data/data/org.nativescript.GeoLocationApp/files/app/tns_modules/tns-core-modules/timer/timer.js:23:13) [<root>]",
	"__zone_symbol__currentTask": {
		"type": "microTask",
		"state": "notScheduled",
		"source": "Promise.then",
		"zone": "angular",
		"cancelFn": null,
		"runCount": 0
	}
}
```

**Comment by TheOnlyMatt** [comment]
I finally succeeded to get the GPS work
I took Tino's code and made some improvements on it, because it was not locating me correctly.

I also noticed, that if you move a little bit in the offices, the location change event can be triggered, which will then give you the correct geolocation data.

**Comment by DimitarTachev** [comment]
As there are a lot of issues with the Android Location Manager and it's not the recommended approach for getting a location on Android, we fully replaced the Android implementation with the Google Play Location Service one (used by Google Maps).

The change is currently on a [pull request](https://github.com/NativeScript/nativescript-geolocation/pull/72) and we are still testing some edge cases. However, you could check if your issues are resolved using the [tachev/location-manager-to-google-play-services](https://github.com/NativeScript/nativescript-geolocation/tree/tachev/location-manager-to-google-play-services) branch.

**Comment by mohammadrafigh** [comment]
@DimitarTachev I tried your branch and still I get timeout.

**Comment by mohammadrafigh** [comment]
today I tested the same app on iOS 11 and I get timeout there too. so the problem is not related to Android side. maybe a Nativescript runtime issue?

**Comment by zbranzov** [comment]
@DimitarTachev @mohammadrafigh  Using your branch and the corresponding demo on Lenovo A6010 Android 5.0.2 I was able to get location using gps service.

**Comment by zbranzov** [comment]
@mohammadrafigh Regarding iOS, be sure you have wifi on. This seems to fix it on my side but I guess this should be a separate discussion for another issue related to iOS.

**Comment by DimitarTachev** [comment]
We closed the issues as the Android implementation is fully replaced by a new one and we are not able to reproduce the timeouts anymore.

You could take a look at the 4.0.0 release notes [here](https://github.com/NativeScript/nativescript-geolocation/releases/tag/v4.0.0).

**Comment by mohammadrafigh** [comment]
ah nice. I can now confirm that the issue is fixed on Android. I don't know why in previous try I got timeout. but now everything works fine. thanks @DimitarTachev .

**Comment by guestisp** [comment]
I'm also getting this.
Tried everything, including the watchLocation trick, but it doesn't solve the issue.
Any idea?

**Comment by guestisp** [comment]
Bump. I get the same issue even in latest version 4.2.1

**Comment by scottmcmu** [comment]
I am getting the same error with version 4.2.2.  I also tried the watchLocation trick.

**Comment by tsonevn** [comment]
Hi @guestisp, @scottmcmu,
Thank you for contacting us.
We reviewed your case, however, we were unable to recreate an issue with the getCurrentLocation method, while using the latest version of the plugin 4.2.2.
Regarding that, it would help if you could open a new issue, where you could provide the following info:
 * NativeScript CLI versions
* tns-core-modules versions
* tns-android versions
* tns-ios versions
* node versions
* npm versions
* sample project, which could be used for debugging
* exact steps which you are using while building the project

This info will help us to recreate the issue and to verify if there is a real problem.
Thank you in advance for your cooperation.

**Comment by guestisp** [comment]
@tsonevn i've opened a new issue

**Comment by pitchinnate** [comment]
I figured out that if you follow the tutorial it is actually incorrect. At least now it currently says to use: 
```
const Geolocation = require("nativescript-geolocation");
const Accuracy = require("tns-core-modules/ui/enums");
...
Geolocation.getCurrentLocation({
            desiredAccuracy: Accuracy.high,
            updateDistance: 0.1,
            timeout: 20000,
          })
```
However I realized that `Accuracy` should be imported as:
```
const { Accuracy } = require("tns-core-modules/ui/enums");
```
if you want to use it that way. Or if you don't change your import statement you can use: `Accuracy.Accuracy.high` on the `desiredAccuracy`.

**Comment by youtpout** [comment]
I have this error, i add timeout 0 for resolve the problem
`Geolocation.getCurrentLocation({desiredAccuracy: Accuracy.high,  timeout: 0 })`

**Comment by jorfranb** [comment]
@youtpout answer worked for me, 
On android emulator the only configuration for geolocations actions (watch and get) is setting 
```
{
desiredAccuracy:3
}
```
If you use anything else will throw an exception for timeout, putting timeout:0 works for another desiredAccuracy value,,,

**Comment by youtpout** [comment]
I try on real device
